name: tinyqsim
channels:
  - defaults
dependencies:
  - python>=3.12
  - more-itertools
  - numpy
  - scipy
  - matplotlib
  - notebook
  - ipython
  - ipympl
  - pytest
  - pip
  - pip:
      - pdoc
      - nb-clean
